[View in Colaboratory](https://colab.research.google.com/github/nifei/understand-neural-network/blob/master/1_auto_gradient.ipynb)

In [1]:
!pip install torch torchvision

    100% |████████████████████████████████| 484.0MB 28kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x5ca3a000 @  0x7ffa4813e1c4 0x46d6a4 0x5fcbcc 0x4c494d 0x54f3c4 0x553aaf 0x54e4c8 0x54f4f6 0x553aaf 0x54efc1 0x54f24d 0x553aaf 0x54efc1 0x54f24d 0x553aaf 0x54efc1 0x54f24d 0x551ee0 0x54e4c8 0x54f4f6 0x553aaf 0x54efc1 0x54f24d 0x551ee0 0x54efc1 0x54f24d 0x551ee0 0x54e4c8 0x54f4f6 0x553aaf 0x54e4c8
    100% |████████████████████████████████| 61kB 17.7MB/s 
    100% |████████████████████████████████| 2.0MB 15.8MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0


In [0]:
import torch

In [31]:
x = torch.Tensor([1.])
x.requires_grad_(True)
print(x)
print(x.requires_grad)

tensor([ 1.])
True


In [32]:
y = x * 3
y

tensor([ 3.])

In [33]:
loss = y - 9
loss

tensor([-6.])

In [0]:
loss.backward()

In [35]:
x.grad

tensor([ 3.])

In [36]:
x.grad.data.zero_()

tensor([ 0.])

In [37]:
x.grad

tensor([ 0.])

In [40]:
print(loss.grad_fn)